vec <- c("MMMM", "537", "MFFM", "526", "MMMF", "549", "FMFM", "498", "MMFM", "514", "FFMM", "490","MFMM", "523", "MFFF", "429", "FMMM", "467", "FMFF", "451", "MMFF", "497", "FFMF", "456", "MFMF", "486", "FFFM", "441", "FMMF", "473", "FFFF", "408")
mat <- matrix(vec, ncol=4, byrow=TRUE)
mat <- rbind(mat[, c(1, 2)], mat[, c(3, 4)])
df <- data.frame(mat, stringsAsFactors=FALSE)
colnames(df) <- c("Sequence", "Freq")
df$Freq <- as.numeric(df$Freq)
ss <- strsplit(df$Sequence, "")
df$NMale <- sapply(ss, function(x) sum(x == "M"))
agg <- aggregate(Freq ~ NMale, data=df, sum)
